; pytest配置 必須要[pytest] --html=report/测试报告2.html --self-contained-html
[pytest]
addopts = -s 
; python_files = test_* 
python_files = test_add_goods.py 
python_classes = Test*
python_functions = test_*
testpaths = ./script/